/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MembersRouteImport } from './routes/members'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ProfileRouteRouteImport } from './routes/profile/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileSocialLinksRouteImport } from './routes/profile/social-links'
import { Route as ProfileSecurityRouteImport } from './routes/profile/security'
import { Route as ProfilePreferencesRouteImport } from './routes/profile/preferences'
import { Route as ProfileMembershipRouteImport } from './routes/profile/membership'
import { Route as ProfileContactRouteImport } from './routes/profile/contact'
import { Route as MembershipManageRouteImport } from './routes/membership/manage'
import { Route as MembersVerifyRouteImport } from './routes/members/verify'
import { Route as AdminMembershipRouteImport } from './routes/admin/membership'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ApiProofsSplatRouteImport } from './routes/api/proofs/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAssetsSplatRouteImport } from './routes/api/assets/$'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRouteRoute = ProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileSocialLinksRoute = ProfileSocialLinksRouteImport.update({
  id: '/social-links',
  path: '/social-links',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileSecurityRoute = ProfileSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfilePreferencesRoute = ProfilePreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileMembershipRoute = ProfileMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const ProfileContactRoute = ProfileContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => ProfileRouteRoute,
} as any)
const MembershipManageRoute = MembershipManageRouteImport.update({
  id: '/membership/manage',
  path: '/membership/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersVerifyRoute = MembersVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => MembersRoute,
} as any)
const AdminMembershipRoute = AdminMembershipRouteImport.update({
  id: '/admin/membership',
  path: '/admin/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProofsSplatRoute = ApiProofsSplatRouteImport.update({
  id: '/api/proofs/$',
  path: '/api/proofs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssetsSplatRoute = ApiAssetsSplatRouteImport.update({
  id: '/api/assets/$',
  path: '/api/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/contact-us': typeof ContactUsRoute
  '/members': typeof MembersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/publications': typeof PublicationsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/membership': typeof AdminMembershipRoute
  '/members/verify': typeof MembersVerifyRoute
  '/membership/manage': typeof MembershipManageRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/social-links': typeof ProfileSocialLinksRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proofs/$': typeof ApiProofsSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/contact-us': typeof ContactUsRoute
  '/members': typeof MembersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/publications': typeof PublicationsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/membership': typeof AdminMembershipRoute
  '/members/verify': typeof MembersVerifyRoute
  '/membership/manage': typeof MembershipManageRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/social-links': typeof ProfileSocialLinksRoute
  '/profile': typeof ProfileIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proofs/$': typeof ApiProofsSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/profile': typeof ProfileRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/agenda': typeof AgendaRoute
  '/contact-us': typeof ContactUsRoute
  '/members': typeof MembersRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/publications': typeof PublicationsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/membership': typeof AdminMembershipRoute
  '/members/verify': typeof MembersVerifyRoute
  '/membership/manage': typeof MembershipManageRoute
  '/profile/contact': typeof ProfileContactRoute
  '/profile/membership': typeof ProfileMembershipRoute
  '/profile/preferences': typeof ProfilePreferencesRoute
  '/profile/security': typeof ProfileSecurityRoute
  '/profile/social-links': typeof ProfileSocialLinksRoute
  '/profile/': typeof ProfileIndexRoute
  '/api/assets/$': typeof ApiAssetsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/proofs/$': typeof ApiProofsSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/about'
    | '/agenda'
    | '/contact-us'
    | '/members'
    | '/privacy-policy'
    | '/publications'
    | '/sign-in'
    | '/sign-up'
    | '/terms-and-conditions'
    | '/admin/dashboard'
    | '/admin/membership'
    | '/members/verify'
    | '/membership/manage'
    | '/profile/contact'
    | '/profile/membership'
    | '/profile/preferences'
    | '/profile/security'
    | '/profile/social-links'
    | '/profile/'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/api/proofs/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agenda'
    | '/contact-us'
    | '/members'
    | '/privacy-policy'
    | '/publications'
    | '/sign-in'
    | '/sign-up'
    | '/terms-and-conditions'
    | '/admin/dashboard'
    | '/admin/membership'
    | '/members/verify'
    | '/membership/manage'
    | '/profile/contact'
    | '/profile/membership'
    | '/profile/preferences'
    | '/profile/security'
    | '/profile/social-links'
    | '/profile'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/api/proofs/$'
  id:
    | '__root__'
    | '/'
    | '/profile'
    | '/about'
    | '/agenda'
    | '/contact-us'
    | '/members'
    | '/privacy-policy'
    | '/publications'
    | '/sign-in'
    | '/sign-up'
    | '/terms-and-conditions'
    | '/admin/dashboard'
    | '/admin/membership'
    | '/members/verify'
    | '/membership/manage'
    | '/profile/contact'
    | '/profile/membership'
    | '/profile/preferences'
    | '/profile/security'
    | '/profile/social-links'
    | '/profile/'
    | '/api/assets/$'
    | '/api/auth/$'
    | '/api/proofs/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProfileRouteRoute: typeof ProfileRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AgendaRoute: typeof AgendaRoute
  ContactUsRoute: typeof ContactUsRoute
  MembersRoute: typeof MembersRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PublicationsRoute: typeof PublicationsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMembershipRoute: typeof AdminMembershipRoute
  MembershipManageRoute: typeof MembershipManageRoute
  ApiAssetsSplatRoute: typeof ApiAssetsSplatRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProofsSplatRoute: typeof ApiProofsSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/social-links': {
      id: '/profile/social-links'
      path: '/social-links'
      fullPath: '/profile/social-links'
      preLoaderRoute: typeof ProfileSocialLinksRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/security': {
      id: '/profile/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof ProfileSecurityRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/preferences': {
      id: '/profile/preferences'
      path: '/preferences'
      fullPath: '/profile/preferences'
      preLoaderRoute: typeof ProfilePreferencesRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/membership': {
      id: '/profile/membership'
      path: '/membership'
      fullPath: '/profile/membership'
      preLoaderRoute: typeof ProfileMembershipRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/profile/contact': {
      id: '/profile/contact'
      path: '/contact'
      fullPath: '/profile/contact'
      preLoaderRoute: typeof ProfileContactRouteImport
      parentRoute: typeof ProfileRouteRoute
    }
    '/membership/manage': {
      id: '/membership/manage'
      path: '/membership/manage'
      fullPath: '/membership/manage'
      preLoaderRoute: typeof MembershipManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/verify': {
      id: '/members/verify'
      path: '/verify'
      fullPath: '/members/verify'
      preLoaderRoute: typeof MembersVerifyRouteImport
      parentRoute: typeof MembersRoute
    }
    '/admin/membership': {
      id: '/admin/membership'
      path: '/admin/membership'
      fullPath: '/admin/membership'
      preLoaderRoute: typeof AdminMembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/proofs/$': {
      id: '/api/proofs/$'
      path: '/api/proofs/$'
      fullPath: '/api/proofs/$'
      preLoaderRoute: typeof ApiProofsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assets/$': {
      id: '/api/assets/$'
      path: '/api/assets/$'
      fullPath: '/api/assets/$'
      preLoaderRoute: typeof ApiAssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteRouteChildren {
  ProfileContactRoute: typeof ProfileContactRoute
  ProfileMembershipRoute: typeof ProfileMembershipRoute
  ProfilePreferencesRoute: typeof ProfilePreferencesRoute
  ProfileSecurityRoute: typeof ProfileSecurityRoute
  ProfileSocialLinksRoute: typeof ProfileSocialLinksRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteRouteChildren: ProfileRouteRouteChildren = {
  ProfileContactRoute: ProfileContactRoute,
  ProfileMembershipRoute: ProfileMembershipRoute,
  ProfilePreferencesRoute: ProfilePreferencesRoute,
  ProfileSecurityRoute: ProfileSecurityRoute,
  ProfileSocialLinksRoute: ProfileSocialLinksRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteRouteWithChildren = ProfileRouteRoute._addFileChildren(
  ProfileRouteRouteChildren,
)

interface MembersRouteChildren {
  MembersVerifyRoute: typeof MembersVerifyRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersVerifyRoute: MembersVerifyRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProfileRouteRoute: ProfileRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AgendaRoute: AgendaRoute,
  ContactUsRoute: ContactUsRoute,
  MembersRoute: MembersRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PublicationsRoute: PublicationsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMembershipRoute: AdminMembershipRoute,
  MembershipManageRoute: MembershipManageRoute,
  ApiAssetsSplatRoute: ApiAssetsSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProofsSplatRoute: ApiProofsSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
